name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Query table
        run: |
          curl \
            "https://dtidkwzdyahwmtbexxzx.supabase.co/rest/v1/messages_contact?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"
